-- MySQL Script generated by MySQL Workbench
-- Tue 29 Oct 2019 10:56:41 AM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SEMESTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SEMESTER` (
  `id` INT NOT NULL,
  `year` INT NULL,
  `season` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DEPARTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DEPARTMENT` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `building` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MAJOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MAJOR` (
  `id` INT NOT NULL,
  `department` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `department_idx` (`department` ASC),
  CONSTRAINT `department`
    FOREIGN KEY (`department`)
    REFERENCES `mydb`.`DEPARTMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOCATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOCATION` (
  `id` INT NOT NULL,
  `building` VARCHAR(45) NULL,
  `room` INT NULL,
  `purpose` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FACULTY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FACULTY` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `department` INT NULL,
  `startDate` INT NULL,
  `endDate` INT NULL,
  `office` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `department_idx` (`department` ASC),
  INDEX `startDate_idx` (`startDate` ASC),
  INDEX `endDate_idx` (`endDate` ASC),
  INDEX `office_idx` (`office` ASC),
  CONSTRAINT `department`
    FOREIGN KEY (`department`)
    REFERENCES `mydb`.`DEPARTMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `startDate`
    FOREIGN KEY (`startDate`)
    REFERENCES `mydb`.`SEMESTER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `endDate`
    FOREIGN KEY (`endDate`)
    REFERENCES `mydb`.`SEMESTER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `office`
    FOREIGN KEY (`office`)
    REFERENCES `mydb`.`LOCATION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STUDENT` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `graduationDate` INT NULL,
  `major` INT NULL,
  `adviser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `graduationDate_idx` (`graduationDate` ASC),
  INDEX `major_idx` (`major` ASC),
  INDEX `adviser_idx` (`adviser` ASC),
  CONSTRAINT `graduationDate`
    FOREIGN KEY (`graduationDate`)
    REFERENCES `mydb`.`SEMESTER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `major`
    FOREIGN KEY (`major`)
    REFERENCES `mydb`.`MAJOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `adviser`
    FOREIGN KEY (`adviser`)
    REFERENCES `mydb`.`FACULTY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COURSE` (
  `id` INT NOT NULL,
  `department` INT NULL,
  `abbreviation` VARCHAR(45) NULL,
  `number` INT NULL,
  `title` VARCHAR(45) NULL,
  `credits` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `department_idx` (`department` ASC),
  CONSTRAINT `department`
    FOREIGN KEY (`department`)
    REFERENCES `mydb`.`DEPARTMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SECTION` (
  `id` INT NOT NULL,
  `course` INT NULL,
  `instructor` INT NULL,
  `offered` INT NULL,
  `location` INT NULL,
  `startHour` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `course_idx` (`course` ASC),
  INDEX `instructor_idx` (`instructor` ASC),
  INDEX `offered_idx` (`offered` ASC),
  INDEX `location_idx` (`location` ASC),
  CONSTRAINT `course`
    FOREIGN KEY (`course`)
    REFERENCES `mydb`.`COURSE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instructor`
    FOREIGN KEY (`instructor`)
    REFERENCES `mydb`.`FACULTY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `offered`
    FOREIGN KEY (`offered`)
    REFERENCES `mydb`.`SEMESTER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `location`
    FOREIGN KEY (`location`)
    REFERENCES `mydb`.`LOCATION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENROLLMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENROLLMENT` (
  `id` INT NOT NULL,
  `student` INT NULL,
  `section` INT NULL,
  `grade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `student_idx` (`student` ASC),
  INDEX `section_idx` (`section` ASC),
  CONSTRAINT `student`
    FOREIGN KEY (`student`)
    REFERENCES `mydb`.`STUDENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `section`
    FOREIGN KEY (`section`)
    REFERENCES `mydb`.`SECTION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`student` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view2` (`name` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;
CREATE  OR REPLACE VIEW `view1` AS 
	select student
    from STUDENT join Major
    where name="management";

-- -----------------------------------------------------
-- View `mydb`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view2`;
USE `mydb`;
CREATE  OR REPLACE VIEW `view2` AS
	select name
    from STUDENT join FACULTY
    where adviser="nancy";

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`SEMESTER`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`SEMESTER` (`id`, `year`, `season`) VALUES (1, 2016, 'fall');
INSERT INTO `mydb`.`SEMESTER` (`id`, `year`, `season`) VALUES (2, 2017, 'spring');
INSERT INTO `mydb`.`SEMESTER` (`id`, `year`, `season`) VALUES (3, 2017, 'fall');
INSERT INTO `mydb`.`SEMESTER` (`id`, `year`, `season`) VALUES (4, 2018, 'spring');
INSERT INTO `mydb`.`SEMESTER` (`id`, `year`, `season`) VALUES (5, 2018, 'fall');
INSERT INTO `mydb`.`SEMESTER` (`id`, `year`, `season`) VALUES (6, 2019, 'spring');
INSERT INTO `mydb`.`SEMESTER` (`id`, `year`, `season`) VALUES (7, 2019, 'fall');
INSERT INTO `mydb`.`SEMESTER` (`id`, `year`, `season`) VALUES (8, 2020, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`DEPARTMENT`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`DEPARTMENT` (`id`, `name`, `building`) VALUES (1, 'compsci', 'olin');
INSERT INTO `mydb`.`DEPARTMENT` (`id`, `name`, `building`) VALUES (2, 'management', 'olin');
INSERT INTO `mydb`.`DEPARTMENT` (`id`, `name`, `building`) VALUES (3, 'math', 'olin');
INSERT INTO `mydb`.`DEPARTMENT` (`id`, `name`, `building`) VALUES (4, 'english', 'main');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`MAJOR`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`MAJOR` (`id`, `department`, `name`) VALUES (1, 1, 'compsci');
INSERT INTO `mydb`.`MAJOR` (`id`, `department`, `name`) VALUES (2, 2, 'management');
INSERT INTO `mydb`.`MAJOR` (`id`, `department`, `name`) VALUES (3, 3, 'math');
INSERT INTO `mydb`.`MAJOR` (`id`, `department`, `name`) VALUES (4, 4, 'english');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`LOCATION`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`LOCATION` (`id`, `building`, `room`, `purpose`) VALUES (1, 'olin', 202, 'compsci');
INSERT INTO `mydb`.`LOCATION` (`id`, `building`, `room`, `purpose`) VALUES (2, 'olin', 112, 'compsci');
INSERT INTO `mydb`.`LOCATION` (`id`, `building`, `room`, `purpose`) VALUES (3, 'olin', 207, 'management');
INSERT INTO `mydb`.`LOCATION` (`id`, `building`, `room`, `purpose`) VALUES (4, 'olin', 213, 'management');
INSERT INTO `mydb`.`LOCATION` (`id`, `building`, `room`, `purpose`) VALUES (5, 'olin', 201, 'math');
INSERT INTO `mydb`.`LOCATION` (`id`, `building`, `room`, `purpose`) VALUES (6, 'main', 212, 'english');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`FACULTY`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`FACULTY` (`id`, `name`, `department`, `startDate`, `endDate`, `office`) VALUES (1, 'roman', compsci, 09/03/19, 12/16/19, 319);
INSERT INTO `mydb`.`FACULTY` (`id`, `name`, `department`, `startDate`, `endDate`, `office`) VALUES (2, 'kent', compsci, 09/04/19, 12/15/19, 320);
INSERT INTO `mydb`.`FACULTY` (`id`, `name`, `department`, `startDate`, `endDate`, `office`) VALUES (3, 'patton', management, 09/03/19, 12/16/19, 303);
INSERT INTO `mydb`.`FACULTY` (`id`, `name`, `department`, `startDate`, `endDate`, `office`) VALUES (4, 'don', management, 02/07/20, 06/24/19, 302);
INSERT INTO `mydb`.`FACULTY` (`id`, `name`, `department`, `startDate`, `endDate`, `office`) VALUES (5, 'kyle', math, 02/07/20, 06/24/20, 315);
INSERT INTO `mydb`.`FACULTY` (`id`, `name`, `department`, `startDate`, `endDate`, `office`) VALUES (6, 'nancy', english, 09/04/19, 12/15/19, 217);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`STUDENT`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`STUDENT` (`id`, `name`, `graduationDate`, `major`, `adviser`) VALUES (1, 'alex', 2020, management, patton);
INSERT INTO `mydb`.`STUDENT` (`id`, `name`, `graduationDate`, `major`, `adviser`) VALUES (2, 'carson', 2021, management, don);
INSERT INTO `mydb`.`STUDENT` (`id`, `name`, `graduationDate`, `major`, `adviser`) VALUES (3, 'sam', 2020, compsci, roman);
INSERT INTO `mydb`.`STUDENT` (`id`, `name`, `graduationDate`, `major`, `adviser`) VALUES (4, 'daniel', 2022, compsci, kent);
INSERT INTO `mydb`.`STUDENT` (`id`, `name`, `graduationDate`, `major`, `adviser`) VALUES (5, 'brooke', 2023, math, kyle);
INSERT INTO `mydb`.`STUDENT` (`id`, `name`, `graduationDate`, `major`, `adviser`) VALUES (6, 'karissa', 2021, english, nancy);
INSERT INTO `mydb`.`STUDENT` (`id`, `name`, `graduationDate`, `major`, `adviser`) VALUES (7, 'sydney', 2023, compsci, roman);
INSERT INTO `mydb`.`STUDENT` (`id`, `name`, `graduationDate`, `major`, `adviser`) VALUES (8, 'jake', 2022, management, patton);
INSERT INTO `mydb`.`STUDENT` (`id`, `name`, `graduationDate`, `major`, `adviser`) VALUES (9, 'kyle', 2021, math, kyle);
INSERT INTO `mydb`.`STUDENT` (`id`, `name`, `graduationDate`, `major`, `adviser`) VALUES (10, 'travis', 2020, english, nancy);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`COURSE`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`COURSE` (`id`, `department`, `abbreviation`, `number`, `title`, `credits`) VALUES (1, 1, 'CS', 150, 'Intro to Programming', 4);
INSERT INTO `mydb`.`COURSE` (`id`, `department`, `abbreviation`, `number`, `title`, `credits`) VALUES (2, 2, 'MGT', 352, 'Human Resources', 4);
INSERT INTO `mydb`.`COURSE` (`id`, `department`, `abbreviation`, `number`, `title`, `credits`) VALUES (3, 3, 'MATH', 454, 'Principles of Real Anaylsis', 4);
INSERT INTO `mydb`.`COURSE` (`id`, `department`, `abbreviation`, `number`, `title`, `credits`) VALUES (4, 4, 'ENG', 231, 'Film', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`SECTION`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`SECTION` (`id`, `course`, `instructor`, `offered`, `location`, `startHour`) VALUES (1, 1, roman, 2016, olin, '8am');
INSERT INTO `mydb`.`SECTION` (`id`, `course`, `instructor`, `offered`, `location`, `startHour`) VALUES (2, 1, roman, 2016, olin, '10am');
INSERT INTO `mydb`.`SECTION` (`id`, `course`, `instructor`, `offered`, `location`, `startHour`) VALUES (3, 1, kent, 2017, olin, '12pm');
INSERT INTO `mydb`.`SECTION` (`id`, `course`, `instructor`, `offered`, `location`, `startHour`) VALUES (4, 1, kent, 2018, olin, '8am');
INSERT INTO `mydb`.`SECTION` (`id`, `course`, `instructor`, `offered`, `location`, `startHour`) VALUES (5, 2, patton, 2018, olin, '10am');
INSERT INTO `mydb`.`SECTION` (`id`, `course`, `instructor`, `offered`, `location`, `startHour`) VALUES (6, 2, don, 2019, olin, '2pm');
INSERT INTO `mydb`.`SECTION` (`id`, `course`, `instructor`, `offered`, `location`, `startHour`) VALUES (7, 4, nancy, 2020, main, '8am');
INSERT INTO `mydb`.`SECTION` (`id`, `course`, `instructor`, `offered`, `location`, `startHour`) VALUES (8, 4, nancy, 2017, main, '10am');
INSERT INTO `mydb`.`SECTION` (`id`, `course`, `instructor`, `offered`, `location`, `startHour`) VALUES (9, 3, kyle, 2019, olin, '12pm');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ENROLLMENT`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (1, sam, 1, 'B');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (2, alex, 2, 'A');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (3, karissa, 7, 'C');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (4, sydney, 6, 'B');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (5, tucker, 9, 'D');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (6, ana, 3, 'D');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (7, jake, 5, 'C');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (8, kyle, 4, 'B');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (9, lucy, 8, 'A');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (10, chris, 2, 'B');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (11, mitch, 7, 'B');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (12, bob, 5, 'C');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (13, amy, 9, 'D');
INSERT INTO `mydb`.`ENROLLMENT` (`id`, `student`, `section`, `grade`) VALUES (14, john, 1, NULL);

COMMIT;

